### ISSUE TITLE
Use without Alloy?

### ISSUE THREAD

**Issue by DFoxinator** [m1ga/com.miga.gifview#3]
Hi,

Thanks for creating this module. Is it possible to use it without Alloy and instead just using straight JavaScript?

Any help is appreciated.

Thanks.

**Comment by DFoxinator** [comment]
I tried doing something like:
modulereference.createGifView({
			image: "image.gif"
}); 

but I don't see to get any output

**Comment by DFoxinator** [comment]
Sorry, one more question - can the module be used with either a remote image url or an image as a blob? Or does it only work with an image contained in the assets of the project?

**Comment by DFoxinator** [comment]
I was able to get it to work with a local project asset, but looking at the code, it seems it doesn't support remote images. I'm not that familiar with the Titanium Java SDK, but I'm dabbling around looking for a semi-easy way to load from a remote image. Any ideas? I'd be happy to open a PR if I can figure out how to do it.

**Comment by DFoxinator** [comment]
Or maybe just taking a blob as the GIF, whatever would be easier.

**Comment by m1ga** [comment]
I'll add remote support soon. Have added it in my https://github.com/m1ga/com.miga.roundview module and can port it over to this one. Blob support sounds like a good idea too.

**Comment by DFoxinator** [comment]
Thanks! I appreciate the guidance. I will try to port that over and see how it goes!

**Comment by m1ga** [comment]
version 1.3 is ready:
- remote images
- js example in the readme

blob support will be added in the next version

**Comment by DFoxinator** [comment]
Thank you so much! It works great, I just implemented it into my project. I'll let you know if I come across any issues, but thanks again and great work!
